const animes = [
    {
        img: 'img/anime_dragonBall.png',
        name: 'Dragon ball',
        year: '1980 - 1990',
        episodes: '+ 24',
        genre: 'Action',
    },
    {
        img: 'img/anime_evangelion.jpg',
        name: 'Evangelion',
        year: '1990 - 2005',
        episodes: '+ 24',
        genre: 'Action',
    },
    {
        img: 'img/anime_naruto.jpg',
        name: 'Naruto',
        year: '1990 - 2005',
        episodes: '+ 24',
        genre: 'Action',
    },
    {
        img: 'img/anime_sailorMoon.jpg',
        name: 'Sailor moon',
        year: '1990 - 2005',
        episodes: '+ 24',
        genre: 'Romance',
    },
    {
        img: 'img/anime_kobayashi.jpg',
        name: 'Koabyashi san',
        year: '2005 - 2023',
        episodes: '12 - 24',
        genre: 'Comedy',
    },
    {
        img: 'img/anime_kamisama.jpg',
        name: 'Kamisama hajimemashita',
        year: '2005 - 2023',
        episodes: '12 - 24',
        genre: 'Romance',
    },
    {
        img: 'img/anime_onepush.png',
        name: 'One puchman',
        year: '2005 - 2023',
        episodes: '12 - 24',
        genre: 'Action',
    },
    {
        img: 'img/anime_onePiece.jpg',
        name: 'One piece',
        year: '1990 - 2005',
        episodes: '+ 24',
        genre: 'Action',
    },
    {
        img: 'img/anime_hellsing.jpg',
        name: 'Hellsing',
        year: '1990 - 2005',
        episodes: '01 - 12',
        genre: 'Action',
    },
    {
        img: 'img/anime_pokemon.jpg',
        name: 'Pokemon',
        year: '1980 - 1990',
        episodes: '+ 24',
        genre: 'Comedy',
    },
    {
        img: 'img/anime_demon.jpg',
        name: 'Demon slayer',
        year: '2005 - 2023',
        episodes: '12 - 24',
    },
    {
        img: 'img/anime_bochiRock.jpg',
        name: 'Bochi the rock',
        year: '2005 - 2023',
        episodes: '01 - 12',
        genre: 'Comedy',
    },
    {
        img: 'img/anime_yourName.png',
        name: 'Your name',
        year: '2005 - 2023',
        episodes: '01 - 12',
        genre: 'Romance',
    },
    {
        img: 'img/anime_voiceSilent.jpg',
        name: 'Silent voice',
        year: '2005 - 2023',
        episodes: '01 - 12',
        genre: 'Romance',
    },
    {
        img: 'img/anime_kakegurui.jpg',
        name: 'Kakegurui',
        year: '2005 - 2023',
        episodes: '12 - 24',
        genre: 'Comedy',
    },
];